module.exports = {
    AWS_GW_WS: process.env.AWS_GW_WS,
    AWS_REGION: process.env.AWS_REGION,
    AWS_TRANSLATE_PORT: 3600,
    CAPTIONS_TRANSLATIONS_LANGUAGE_CODES: process.env.CAPTIONS_TRANSLATIONS_LANGUAGE_CODES,
    WRITER_WEBSOCKET_SENDTRANSCRIPTION_ROUTE: "sendtranscription",
    DEFAULT_SOURCE_LANGUAGE_CODE: "en",
};
